version: "3.9"

services:
  minecraft:
    build: ./minecraft/
    network_mode: bridge
    ports:
      - "25565:25565"
      - "25575:25575"
      - "8123:8123"
    volumes:
      - ./minecraft/server:/var/minecraft/server  
  nginx-proxy:
    build: ./nginx-proxy/
    network_mode: bridge
    ports:
      - "80:80"
  backup-daemon:
    build: ./backup-daemon/
    volumes:
      - ./backup-daemon/backup:/var/backup-daemon/backup
      - ./minecraft/server:/var/backup-daemon/server